[Unit]
Requires=harmonia-matrix-prepare.service
After=harmonia-matrix-prepare.service postgresql.service

[Service]
User=matrix-synapse
Group=matrix-synapse
RuntimeDirectory=matrix-synapse
RuntimeDirectoryMode=0750
StateDirectory=matrix-synapse
StateDirectoryMode=0750
LogsDirectory=matrix-synapse
LogsDirectoryMode=0750
UMask=0027
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=strict
ProtectHome=yes
ReadWritePaths=/var/lib/matrix-synapse /var/log/matrix-synapse /run/matrix-synapse
