[Unit]
Requires=harmonia-matrix-prepare.service
After=harmonia-matrix-prepare.service postgresql.service

[Service]
User=matrix-synapse
Group=matrix-synapse
RuntimeDirectory=matrix-synapse
RuntimeDirectoryMode=0750
StateDirectory=matrix-synapse
StateDirectoryMode=0750
LogsDirectory=matrix-synapse
LogsDirectoryMode=0750
