[piwigo]
user = piwigo
group = piwigo
listen = 127.0.0.1:8080
;listen.owner = piwigo
;listen.group = www-data
;listen.mode = 0660

pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

chdir = /opt/piwigo/piwigo
php_admin_value[open_basedir] = /opt/piwigo/piwigo:/tmp:/mnt/nas/photos:/mnt/nas:/opt/piwigo

; Add error logging
php_admin_flag[log_errors] = on
php_admin_value[error_log] = /opt/piwigo/piwigo/local/php-fpm-error.log
php_admin_value[display_errors] = on

; Add FastCGI parameters
env[SCRIPT_FILENAME] = $document_root$fastcgi_script_name
env[REQUEST_METHOD] = $request_method
env[QUERY_STRING] = $query_string
env[CONTENT_TYPE] = $content_type
env[CONTENT_LENGTH] = $content_length
env[SCRIPT_NAME] = $fastcgi_script_name
env[REQUEST_URI] = $request_uri
env[DOCUMENT_URI] = $document_uri
env[DOCUMENT_ROOT] = $document_root
env[SERVER_PROTOCOL] = $server_protocol
