server:
    include: /etc/unbound/blocklist.conf
    interface-automatic: yes
    port: 53
    do-ip4: yes
    do-ip6: no
    access-control: 192.168.0.0/16 allow
    access-control: 100.64.0.0/10 allow
    tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt

local-zone: "home.arpa." static
local-zone: "home.local." static

local-data: "home.arpa. IN A 192.168.123.1"
local-data: "home.local. IN A 192.168.123.1"
local-data: "git.home.arpa. IN A 192.168.123.1"
local-data: "vault.home.arpa. IN A 192.168.123.1"
local-data: "docs.home.arpa. IN A 192.168.123.1"
local-data: "music.home.arpa. IN A 192.168.123.1"
local-data: "jellyfin.home.arpa. IN A 192.168.123.1"
local-data: "crown.home.arpa. IN A 192.168.123.1"
local-data: "photos.home.arpa. IN A 192.168.123.1"
local-data: "books.home.arpa. IN A 192.168.123.1"
local-data: "files.home.arpa. IN A 192.168.123.1"
local-data: "transmission.home.arpa. IN A 192.168.123.1"
local-data: "rss.home.arpa. IN A 192.168.123.1"
local-data: "mattermost.home.arpa. IN A 192.168.123.1"
local-data: "chat.home.arpa. IN A 192.168.123.1"
local-data: "search.home.arpa. IN A 192.168.123.1"
local-data: "firecrawl.home.arpa. IN A 192.168.123.1"
local-data: "unifi.home.arpa. IN A 192.168.123.1"
local-data: "ci.home.arpa. IN A 192.168.123.1"
local-data: "godshand.home.arpa. IN A 192.168.123.1"
local-data: "recipes.home.arpa. IN A 192.168.123.1"
local-data: "audiobooks.home.arpa. IN A 192.168.123.1"
local-data: "homeserver.home.arpa. IN A 192.168.123.1"
local-data: "bigrig.home.arpa. IN A 192.168.123.8"
local-data: "console.home.arpa. IN A 192.168.123.1"
local-data: "laptop-01.home.arpa. IN A 192.168.123.19"
local-data: "laptop.home.arpa. IN A 192.168.123.21"
local-data: "laptop-02.home.arpa. IN A 192.168.123.21"
local-data: "tv.home.arpa. IN A 192.168.123.17"
local-data: "chia-harvester-03.home.arpa. IN A 192.168.123.27"
local-data: "chia-harvester-04.home.arpa. IN A 192.168.123.23"
local-data: "chia-harvester-05.home.arpa. IN A 192.168.123.28"
local-data: "chia-harvester-01.home.arpa. IN A 192.168.123.24"
local-data: "chia-farmer-01.home.arpa. IN A 192.168.123.25"
local-data: "farmer.home.arpa. IN A 192.168.123.25"
local-data: "arcadia.home.arpa. IN A 192.168.123.1"
local-data: "coronatio.home.arpa. IN A 192.168.123.1"
local-data: "chia-harvester-02.home.arpa. IN A 192.168.123.26"
local-data: "bigrig. IN A 192.168.123.8"

include-toplevel: "/etc/unbound/unbound.conf.d/*.conf"

forward-zone:
    name: "."
    forward-ssl-upstream: yes
    forward-addr: 9.9.9.9@853
    forward-addr: 149.112.112.112@853
